-- MySQL Script generated by MySQL Workbench
-- Fri Apr 25 19:11:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema m221208
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema m221208
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `m221208` ;
USE `m221208` ;

-- -----------------------------------------------------
-- Table `m221208`.`ATC_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m221208`.`ATC_code` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idATC_code_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m221208`.`producer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m221208`.`producer` (
  `idproducer` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `produce_name` VARCHAR(64) NOT NULL,
  `producercol` VARCHAR(45) NULL,
  PRIMARY KEY (`idproducer`),
  UNIQUE INDEX `idproducer_UNIQUE` (`idproducer` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m221208`.`adverse_effect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m221208`.`adverse_effect` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `efect` VARCHAR(45) NULL,
  `description` TEXT(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idside_effect_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m221208`.`therapeutic_effect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m221208`.`therapeutic_effect` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `effect` VARCHAR(45) NULL,
  `description` TEXT(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m221208`.`active_substance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m221208`.`active_substance` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `strength_mg` INT NULL,
  `side_effect_idside_effect` INT UNSIGNED NOT NULL,
  `therapeutic_effect_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_adverse_effect_side_effect1_idx` (`side_effect_idside_effect` ASC) VISIBLE,
  INDEX `fk_active_substance_therapeutic_effect1_idx` (`therapeutic_effect_id` ASC) VISIBLE,
  CONSTRAINT `fk_adverse_effect_side_effect1`
    FOREIGN KEY (`side_effect_idside_effect`)
    REFERENCES `m221208`.`adverse_effect` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_active_substance_therapeutic_effect1`
    FOREIGN KEY (`therapeutic_effect_id`)
    REFERENCES `m221208`.`therapeutic_effect` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m221208`.`medicament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m221208`.`medicament` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `med_name` VARCHAR(64) NOT NULL,
  `price` DECIMAL NOT NULL,
  `prescription` TINYINT(1) NOT NULL,
  `medicamentcol` VARCHAR(45) NULL,
  `ATC_code_id` INT UNSIGNED NOT NULL,
  `producer_idproducer` INT UNSIGNED NOT NULL,
  `adverse_effect_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `med_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_medicament_ATC_code_idx` (`ATC_code_id` ASC) VISIBLE,
  INDEX `fk_medicament_producer1_idx` (`producer_idproducer` ASC) VISIBLE,
  INDEX `fk_medicament_adverse_effect1_idx` (`adverse_effect_id` ASC) VISIBLE,
  CONSTRAINT `fk_medicament_ATC_code`
    FOREIGN KEY (`ATC_code_id`)
    REFERENCES `m221208`.`ATC_code` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicament_producer1`
    FOREIGN KEY (`producer_idproducer`)
    REFERENCES `m221208`.`producer` (`idproducer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicament_adverse_effect1`
    FOREIGN KEY (`adverse_effect_id`)
    REFERENCES `m221208`.`active_substance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m221208`.`med_form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m221208`.`med_form` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `form` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m221208`.`medicament_has_med_form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m221208`.`medicament_has_med_form` (
  `medicament_id` INT UNSIGNED NOT NULL,
  `med_form_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`medicament_id`, `med_form_id`),
  INDEX `fk_medicament_has_med_form_med_form1_idx` (`med_form_id` ASC) VISIBLE,
  INDEX `fk_medicament_has_med_form_medicament1_idx` (`medicament_id` ASC) VISIBLE,
  CONSTRAINT `fk_medicament_has_med_form_medicament1`
    FOREIGN KEY (`medicament_id`)
    REFERENCES `m221208`.`medicament` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicament_has_med_form_med_form1`
    FOREIGN KEY (`med_form_id`)
    REFERENCES `m221208`.`med_form` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
